# Generated by Django 4.0.2 on 2022-03-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
